### ISSUE TITLE
An error in function varPowNb

### ISSUE THREAD

**Issue by ArcturusZhang** [Samir-ouchene/autoderiv#1]
`TYPE(AD) FUNCTION varPowNb(X,Y) RESULT(Z)

TYPE(AD), INTENT(IN) :: X
REAL(pr), INTENT(IN) :: Y

Z%V  = (X%v)**Y
Z%dv = Y *(X%V)**(Y-1.0)

END FUNCTION!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
according to the formula ((f(x))^{\alpha})' = \alpha * (f(x))^{\alpha-1} * f'(x), there is a missing '*X%dv' in the 5th line.

**Comment by s1291** [comment]
Thank you very much @ufo54153 , I fixed it!
